server:
  port: 8082
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: dataIn
          binder: kafka
        output:
          destination: dataOut
          binder: rabbit
