---
applications:
- name: ticktock-log-sink
  host: ticktock-log-sink
  memory: 2G
  disk_quota: 2G
  instances: 1
  path: /tmp/ticktock-log-sink.jar
  env:
#    LOGGING_FILE: ticktocklog.log
#    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: logfile
#    ENDPOINTS_LOGFILE_SENSITIVE: false
#    SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION: ticktock
    logging.file: ticktocklog.log
    endpoints.logfile.sensitive: false
    spring.cloud.stream.bindings.input.destination: ticktock
    #LOG_EXPRESSION: "'TICKTOCK - TIMESTAMP: '.concat(payload)"
    log.expression: "'TICKTOCK - TIMESTAMP: '.concat(payload)"
services:
- scst-rabbit