---
applications:
- name: partitioning-producer
  host: partitioning-producer
  memory: 2G
  disk_quota: 2G
  instances: 1
  path: ../../partitioning-samples/partitioning-producer/target/partitioning-producer-0.0.1-SNAPSHOT.jar
  env:
    SPRING_APPLICATION_JSON: '{"maven": { "remote-repositories": { "repo1": { "url": "https://repo.spring.io/libs-snapshot"} } } }'
    LOGGING_FILE: partproducer.log
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: logfile
services:
- scst-rabbit