---
applications:
- name: partitioning-consumer3
  host: partitioning-consumer3
  memory: 2G
  disk_quota: 2G
  instances: 1
  path: ../../partitioning-samples/partitioning-consumer-rabbit/target/partitioning-consumer-rabbit-0.0.1-SNAPSHOT.jar
  env:
    SPRING_APPLICATION_JSON: '{"maven": { "remote-repositories": { "repo1": { "url": "https://repo.spring.io/libs-snapshot"} } } }'
    LOGGING_FILE: partconsumer3.log
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: logfile
    SPRING_CLOUD_STREAM_BINDINGS_INPUT_CONSUMER_INSTANCEINDEX: 2
services:
- scst-rabbit