---
applications:
- name: uppercase-transformer
  host: uppercase-transformer
  memory: 2G
  disk_quota: 2G
  instances: 1
  path: ../../processor-samples/uppercase-transformer/target/uppercase-transformer-0.0.1-SNAPSHOT.jar
  env:
    SPRING_APPLICATION_JSON: '{"maven": { "remote-repositories": { "repo1": { "url": "https://repo.spring.io/libs-snapshot"} } } }'
    LOGGING_FILE: uppercase.log
    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: logfile
services:
- scst-rabbit